name: flutter_im_kit
description: A Flutter Im Kit.
version: 1.0.0
homepage: https://github.com/TerenYeung/flutter_im_kit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  extended_text: ^7.0.0
  extended_text_field: ^8.0.0
  flutter_slidable: ^0.6.0
  cached_network_image: ^3.1.0
  photo_view: ^0.12.0
  video_player: ^2.1.14
  chewie_audio: ^1.2.0
  flutter_easyloading: ^3.0.0
  just_audio: ^0.9.7
  wechat_assets_picker: ^6.0.4
  wechat_camera_picker: ^2.3.1
  permission_handler: 10.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  characters: ^1.1.0
  extended_text_library: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/emoji/
    - assets/icon/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
